version: '3.8'

networks:
  my-network:
    driver: bridge

services:
  init-keycloak-config:
    image: alpine
    container_name: init-keycloak-config
    entrypoint: /bin/sh /scripts/prepare-keycloak-config.sh
    volumes:
      - ./test-realm.json:/input/test-realm.json:ro
      - ./scripts:/scripts:ro
      - keycloak-config:/output
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    networks:
      - my-network

  backend:
    container_name: backend
    networks:
      - my-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      VERIFY_JWT_TOKEN_URI: http://keycloak:8080/realms/test-realm/protocol/openid-connect/certs
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    container_name: keycloak
    command: start-dev --import-realm --verbose
    networks:
      - my-network
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/postgres-keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HEALTH_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak-config:/opt/keycloak/data/import
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080" ]
      interval: 15s
      timeout: 2s
      retries: 15

  postgres:
    image: postgres:15.5
    container_name: postgres-keycloak
    networks:
      - my-network
    environment:
      POSTGRES_DB: postgres-keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  keycloak-config: