server:
  port: 8081

spring:
  application:
    name: keycloak-test
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${VERIFY_JWT_TOKEN_URI:http://localhost:8080/realms/test-realm/protocol/openid-connect/certs}
      client:
        registration:
          swagger-ui:
            provider: keycloak
            client-id: ${KEYCLOAK_SWAGGER_CLIENT_ID:swagger-ui}
            client-name: Swagger-ui
            client-secret: ${KEYCLOAK_SWAGGER_CLIENT_SECRET:swagger-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/swagger-ui/oauth2-redirect.html"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/test-realm}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: ${KEYCLOAK_SWAGGER_CLIENT_ID:swagger-ui}
      client-secret: ${KEYCLOAK_SWAGGER_CLIENT_SECRET:swagger-secret}
      scopes: openid,profile,email
      realm: test-realm
      use-pkce-with-authorization-code-grant: true